const Cities = [{
    'VE':[{
        'VE-A':[{
            'VE-A-1': 'Caracas', 
            'VE-A-2': 'El Junquito'
        }], 
        'VE-B': [{
            'VE-B-1' : 'Anaco',
            'VE-B-2' : 'Aragua de Barcelona',
            'VE-B-3' : 'Barcelona',
            'VE-B-4' : 'Boca de Uchire',
            'VE-B-5' : 'Cantaura',
            'VE-B-6' : 'Clarines',
            'VE-B-7' : 'El Chaparro',
            'VE-B-8' : 'El Pao Anzoátegui',
            'VE-B-9' : 'El Tigre',
            'VE-B-10': 'El Tigrito',
            'VE-B-11': 'Guanape',
            'VE-B-12': 'Guanta',
            'VE-B-13': 'Lechería',
            'VE-B-14': 'Onoto',
            'VE-B-16': 'Pariaguán',
            'VE-B-17': 'Píritu',
            'VE-B-18': 'Puerto La Cruz',
            'VE-B-19': 'Puerto Píritu',
            'VE-B-20': 'Sabana de Uchire',
            'VE-B-21': 'San Mateo Anzoátegui',
            'VE-B-22': 'San Pablo Anzoátegui',
            'VE-B-23': 'San Tomé',
            'VE-B-24': 'Santa Ana de Anzoátegui',
            'VE-B-25': 'Santa Fe Anzoátegui',
            'VE-B-26': 'Santa Rosa',
            'VE-B-27': 'Soledad',
            'VE-B-28': 'Urica',
            'VE-B-29': 'Valle de Guanape'
        }],
        'VE-C': [{
            'VE-C-1' : 'Achaguas', 
            'VE-C-2' : 'Biruaca', 
            'VE-C-3' : 'Bruzual', 
            'VE-C-4' : 'El Amparo', 
            'VE-C-5' : 'El Nula', 
            'VE-C-6' : 'Elorza', 
            'VE-C-7' : 'Guasdualito', 
            'VE-C-8' : 'Mantecal', 
            'VE-C-9' : 'Puerto Páez', 
            'VE-C-10': 'San Fernando de Apure',
            'VE-C-11': 'San Juan de Payara'
        }],
        'VE-D': [{
            'VE-D-1' : 'Barbacoas', 
            'VE-D-2' : 'Cagua', 
            'VE-D-3' : 'Camatagua', 
            'VE-D-4' : 'Choroní', 
            'VE-D-5' : 'Colonia Tovar', 
            'VE-D-6' : 'El Consejo', 
            'VE-D-7' : 'La Victoria', 
            'VE-D-8' : 'Las Tejerías', 
            'VE-D-9' : 'Magdaleno', 
            'VE-D-10': 'Maracay', 
            'VE-D-11': 'Ocumare de La Costa', 
            'VE-D-12': 'Palo Negro', 
            'VE-D-13': 'San Casimiro', 
            'VE-D-14': 'San Mateo', 
            'VE-D-15': 'San Sebastián', 
            'VE-D-16': 'Santa Cruz de Aragua', 
            'VE-D-17': 'Tocorón', 
            'VE-D-18': 'Turmero', 
            'VE-D-19': 'Villa de Cura', 
            'VE-D-20': 'Zuata'
        }],
        'VE-E': [{ 
            'VE-E-1' : 'Barinas',
            'VE-E-2' : 'Barinitas',
            'VE-E-3' : 'Barrancas',
            'VE-E-4' : 'Calderas',
            'VE-E-5' : 'Capitanejo',
            'VE-E-6' : 'Ciudad Bolivia',
            'VE-E-7' : 'El Cantón',
            'VE-E-8' : 'Las Veguitas',
            'VE-E-9' : 'Libertad de Barinas',
            'VE-E-10': 'Sabaneta',
            'VE-E-11': 'Santa Bárbara de Barinas',
            'VE-E-12': 'Socopó'
        }],
        'VE-F': [{
            'VE-F-1' : 'Caicara del Orinoco',
            'VE-F-2' : 'Canaima',
            'VE-F-3' : 'Ciudad Bolívar',
            'VE-F-4' : 'Ciudad Piar',
            'VE-F-5' : 'El Callao',
            'VE-F-6' : 'El Dorado',
            'VE-F-7' : 'El Manteco',
            'VE-F-8' : 'El Palmar',
            'VE-F-9' : 'El Pao',
            'VE-F-10': 'Guasipati',
            'VE-F-11': 'Guri',
            'VE-F-12': 'La Paragua',
            'VE-F-13': 'Matanzas',
            'VE-F-14': 'Puerto Ordaz',
            'VE-F-15': 'San Félix',
            'VE-F-16': 'Santa Elena de Uairén',
            'VE-F-17': 'Tumeremo',
            'VE-F-18': 'Unare',
            'VE-F-19': 'Upata'
        }],
        'VE-G': [{
            'VE-G-1' : 'Bejuma',
            'VE-G-2' : 'Belén',
            'VE-G-3' : 'Campo de Carabobo',
            'VE-G-4' : 'Canoabo',
            'VE-G-5' : 'Central Tacarigua',
            'VE-G-6' : 'Chirgua',
            'VE-G-7' : 'Ciudad Alianza',
            'VE-G-8' : 'El Palito',
            'VE-G-9' : 'Guacara',
            'VE-G-10': 'Guigue',
            'VE-G-11': 'Las Trincheras',
            'VE-G-12': 'Los Guayos',
            'VE-G-13': 'Mariara',
            'VE-G-14': 'Miranda',
            'VE-G-15': 'Montalbán',
            'VE-G-16': 'Morón',
            'VE-G-17': 'Naguanagua',
            'VE-G-18': 'Puerto Cabello',
            'VE-G-19': 'San Joaquín',
            'VE-G-20': 'Tocuyito',
            'VE-G-21': 'Urama',
            'VE-G-22': 'Valencia',
            'VE-G-23': 'Vigirimita'
        }],
        'VE-H': [{
            'VE-H-1' : 'Aguirre',
            'VE-H-2' : 'Apartaderos Cojedes',
            'VE-H-3' : 'Arismendi',
            'VE-H-4' : 'Camuriquito',
            'VE-H-5' : 'El Baúl',
            'VE-H-6' : 'El Limón',
            'VE-H-7' : 'El Pao Cojedes',
            'VE-H-8' : 'El Socorro',
            'VE-H-9' : 'La Aguadita',
            'VE-H-10': 'Las Vegas',
            'VE-H-11': 'Libertad de Cojedes',
            'VE-H-12': 'Mapuey',
            'VE-H-13': 'Piñedo',
            'VE-H-14': 'Samancito',
            'VE-H-15': 'San Carlos',
            'VE-H-16': 'Sucre',
            'VE-H-17': 'Tinaco',
            'VE-H-18': 'Tinaquillo',
            'VE-H-19': 'Vallecito'
        }],
        'VE-I': [{
            'VE-I-1' : 'Adícora',
            'VE-I-2' : 'Boca de Aroa',
            'VE-I-3' : 'Cabure',
            'VE-I-4' : 'Capadare',
            'VE-I-5' : 'Capatárida',
            'VE-I-6' : 'Chichiriviche',
            'VE-I-7' : 'Churuguara',
            'VE-I-8' : 'Coro',
            'VE-I-9' : 'Cumarebo',
            'VE-I-10': 'Dabajuro',
            'VE-I-11': 'Judibana',
            'VE-I-12': 'La Cruz de Taratara',
            'VE-I-13': 'La Vela de Coro',
            'VE-I-14': 'Los Taques',
            'VE-I-15': 'Maparari',
            'VE-I-16': 'Mene de Mauroa',
            'VE-I-17': 'Mirimire',
            'VE-I-18': 'Pedregal',
            'VE-I-19': 'Píritu Falcón',
            'VE-I-20': 'Pueblo Nuevo Falcón',
            'VE-I-21': 'Puerto Cumarebo',
            'VE-I-22': 'Punta Cardón',
            'VE-I-23': 'Punto Fijo',
            'VE-I-24': 'San Juan de Los Cayos',
            'VE-I-25': 'San Luis',
            'VE-I-26': 'Santa Ana Falcón',
            'VE-I-27': 'Santa Cruz De Bucaral',
            'VE-I-28': 'Tocopero',
            'VE-I-29': 'Tocuyo de La Costa',
            'VE-I-30': 'Tucacas',
            'VE-I-31': 'Yaracal'
        }],
        'VE-J': [{
            'VE-J-1' : 'Altagracia de Orituco',
            'VE-J-2' : 'Cabruta',
            'VE-J-3' : 'Calabozo',
            'VE-J-4' : 'Camaguán',
            'VE-J-5' : 'Chaguaramas Guárico',
            'VE-J-6' : 'El Socorro',
            'VE-J-7' : 'El Sombrero',
            'VE-J-8' : 'Las Mercedes de Los Llanos',
            'VE-J-9' : 'Lezama',
            'VE-J-10': 'Onoto',
            'VE-J-11': 'Ortíz',
            'VE-J-12': 'San José de Guaribe',
            'VE-J-13': 'San Juan de Los Morros',
            'VE-J-14': 'San Rafael de Laya',
            'VE-J-15': 'Santa María de Ipire',
            'VE-J-16': 'Tucupido',
            'VE-J-17': 'Valle de La Pascua',
            'VE-J-18': 'Zaraza'
        }],
        'VE-K': [{
            'VE-K-1' : 'Aguada Grande',
            'VE-K-2' : 'Atarigua',
            'VE-K-3' : 'Barquisimeto',
            'VE-K-4' : 'Bobare',
            'VE-K-5' : 'Cabudare',
            'VE-K-6' : 'Carora',
            'VE-K-7' : 'Cubiro',
            'VE-K-8' : 'Cují',
            'VE-K-9' : 'Duaca',
            'VE-K-10': 'El Manzano',
            'VE-K-11': 'El Tocuyo',
            'VE-K-12': 'Guaríco',
            'VE-K-13': 'Humocaro Alto',
            'VE-K-14': 'Humocaro Bajo',
            'VE-K-15': 'La Miel',
            'VE-K-16': 'Moroturo',
            'VE-K-17': 'Quíbor',
            'VE-K-18': 'Río Claro',
            'VE-K-29': 'Sanare',
            'VE-K-20': 'Santa Inés',
            'VE-K-21': 'Sarare',
            'VE-K-22': 'Siquisique',
            'VE-K-23': 'Tintorero'
        }],
        'VE-L': [{
            'VE-L-1' : 'Apartaderos Mérida',
            'VE-L-2' : 'Arapuey',
            'VE-L-3' : 'Bailadores',
            'VE-L-4' : 'Caja Seca',
            'VE-L-5' : 'Canaguá',
            'VE-L-6' : 'Chachopo',
            'VE-L-7' : 'Chiguara',
            'VE-L-8' : 'Ejido',
            'VE-L-9' : 'El Vigía',
            'VE-L-10': 'La Azulita',
            'VE-L-11': 'La Playa',
            'VE-L-12': 'Lagunillas Mérida',
            'VE-L-13': 'Mérida',
            'VE-L-14': 'Mesa de Bolívar',
            'VE-L-15': 'Mucuchíes',
            'VE-L-16': 'Mucujepe',
            'VE-L-17': 'Mucuruba',
            'VE-L-18': 'Nueva Bolivia',
            'VE-L-19': 'Palmarito',
            'VE-L-20': 'Pueblo Llano',
            'VE-L-21': 'Santa Cruz de Mora',
            'VE-L-22': 'Santa Elena de Arenales',
            'VE-L-23': 'Santo Domingo',
            'VE-L-24': 'Tabáy',
            'VE-L-25': 'Timotes',
            'VE-L-26': 'Torondoy',
            'VE-L-27': 'Tovar',
            'VE-L-28': 'Tucani',
            'VE-L-29': 'Zea'
        }],
        'VE-M': [{
            'VE-M-1' : 'Araguita',
            'VE-M-2' : 'Carrizal',
            'VE-M-3' : 'Caucagua',
            'VE-M-4' : 'Chaguaramas Miranda',
            'VE-M-5' : 'Charallave',
            'VE-M-6' : 'Chirimena',
            'VE-M-7' : 'Chuspa',
            'VE-M-8' : 'Cúa',
            'VE-M-9' : 'Cupira',
            'VE-M-10': 'Curiepe',
            'VE-M-11': 'El Guapo',
            'VE-M-12': 'El Jarillo',
            'VE-M-13': 'Filas de Mariche',
            'VE-M-14': 'Guarenas',
            'VE-M-15': 'Guatire',
            'VE-M-16': 'Higuerote',
            'VE-M-17': 'Los Anaucos',
            'VE-M-18': 'Los Teques',
            'VE-M-19': 'Ocumare del Tuy',
            'VE-M-20': 'Panaquire',
            'VE-M-21': 'Paracotos',
            'VE-M-22': 'Río Chico',
            'VE-M-23': 'San Antonio de Los Altos',
            'VE-M-24': 'San Diego de Los Altos',
            'VE-M-25': 'San Fernando del Guapo',
            'VE-M-26': 'San Francisco de Yare',
            'VE-M-27': 'San José de Los Altos',
            'VE-M-28': 'San José de Río Chico',
            'VE-M-29': 'San Pedro de Los Altos',
            'VE-M-30': 'Santa Lucía',
            'VE-M-31': 'Santa Teresa',
            'VE-M-32': 'Tacarigua de La Laguna',
            'VE-M-33': 'Tacarigua de Mamporal',
            'VE-M-34': 'Tácata',
            'VE-M-35': 'Turumo'
        }],
        'VE-N': [{
            'VE-N-1' : 'Aguasay',
            'VE-N-2' : 'Aragua de Maturín',
            'VE-N-3' : 'Barrancas del Orinoco',
            'VE-N-4' : 'Caicara de Maturín',
            'VE-N-5' : 'Caripe',
            'VE-N-6' : 'Caripito',
            'VE-N-7' : 'Chaguaramal',
            'VE-N-8' : 'Chaguaramas Monagas',
            'VE-N-9' : 'El Furrial',
            'VE-N-10': 'El Tejero',
            'VE-N-11': 'Jusepín',
            'VE-N-12': 'La Toscana',
            'VE-N-13': 'Maturín',
            'VE-N-14': 'Miraflores',
            'VE-N-15': 'Punta de Mata',
            'VE-N-16': 'Quiriquire',
            'VE-N-17': 'San Antonio de Maturín',
            'VE-N-18': 'San Vicente Monagas',
            'VE-N-19': 'Santa Bárbara',
            'VE-N-20': 'Temblador',
            'VE-N-21': 'Teresen',
            'VE-N-22': 'Uracoa'
        }],
        'VE-O': [{
            'VE-O-1' : 'Altagracia',
            'VE-O-2' : 'Boca de Pozo',
            'VE-O-3' : 'Boca de Río',
            'VE-O-4' : 'El Espinal',
            'VE-O-5' : 'El Valle del Espíritu Santo',
            'VE-O-6' : 'El Yaque',
            'VE-O-7' : 'Juangriego',
            'VE-O-8' : 'La Asunción',
            'VE-O-9' : 'La Guardia',
            'VE-O-10': 'Pampatar',
            'VE-O-11': 'Porlamar',
            'VE-O-12': 'Puerto Fermín',
            'VE-O-13': 'Punta de Piedras',
            'VE-O-14': 'San Francisco de Macanao',
            'VE-O-15': 'San Juan Bautista',
            'VE-O-16': 'San Pedro de Coche',
            'VE-O-17': 'Santa Ana de Nueva Esparta',
            'VE-O-18': 'Villa Rosa'
        }],
        'VE-P': [{
            'VE-P-1' : 'Acarigua',
            'VE-P-3' : 'Agua Blanca',
            'VE-P-4' : 'Araure',
            'VE-P-5' : 'Biscucuy',
            'VE-P-6' : 'Boconoito',
            'VE-P-7' : 'Campo Elías',
            'VE-P-8' : 'Chabasquén',
            'VE-P-9' : 'Guanare',
            'VE-P-10': 'Guanarito',
            'VE-P-11': 'La Aparición',
            'VE-P-13': 'La Misión',
            'VE-P-14': 'Mesa de Cavacas',
            'VE-P-15': 'Ospino',
            'VE-P-16': 'Papelón',
            'VE-P-17': 'Payara',
            'VE-P-18': 'Pimpinela',
            'VE-P-19': 'Píritu de Portuguesa',
            'VE-P-20': 'San Rafael de Onoto',
            'VE-P-21': 'Santa Rosalía',
            'VE-P-22': 'Turén'
        }],
        'VE-R': [{
            'VE-R-1' : 'Altos de Sucre',
            'VE-R-2' : 'Araya',
            'VE-R-3' : 'Cariaco',
            'VE-R-4' : 'Carúpano',
            'VE-R-5' : 'Casanay',
            'VE-R-6' : 'Cumaná',
            'VE-R-7' : 'Cumanacoa',
            'VE-R-8' : 'El Morro Puerto Santo',
            'VE-R-9' : 'El Pilar',
            'VE-R-10': 'El Poblado',
            'VE-R-11': 'Guaca',
            'VE-R-12': 'Guiria',
            'VE-R-13': 'Irapa',
            'VE-R-14': 'Manicuare',
            'VE-R-15': 'Mariguitar',
            'VE-R-16': 'Río Caribe',
            'VE-R-17': 'San Antonio del Golfo',
            'VE-R-18': 'San José de Aerocuar',
            'VE-R-19': 'San Vicente de Sucre',
            'VE-R-20': 'Santa Fe de Sucre',
            'VE-R-21': 'Tunapuy',
            'VE-R-22': 'Yaguaraparo',
            'VE-R-23': 'Yoco'
        }],
        'VE-S': [{
            'VE-S-1' : 'Abejales',
            'VE-S-2' : 'Borota',
            'VE-S-3' : 'Bramon',
            'VE-S-4' : 'Capacho',
            'VE-S-5' : 'Colón',
            'VE-S-6' : 'Coloncito',
            'VE-S-7' : 'Cordero',
            'VE-S-8' : 'El Cobre',
            'VE-S-9' : 'El Pinal',
            'VE-S-10': 'Independencia',
            'VE-S-11': 'La Fría',
            'VE-S-12': 'La Grita',
            'VE-S-13': 'La Pedrera',
            'VE-S-14': 'La Tendida',
            'VE-S-15': 'Las Delicias',
            'VE-S-16': 'Las Hernández',
            'VE-S-17': 'Lobatera',
            'VE-S-18': 'Michelena',
            'VE-S-19': 'Palmira',
            'VE-S-20': 'Pregonero',
            'VE-S-21': 'Queniquea',
            'VE-S-22': 'Rubio',
            'VE-S-23': 'San Antonio del Tachira',
            'VE-S-24': 'San Cristobal',
            'VE-S-25': 'San José de Bolívar',
            'VE-S-26': 'San Josecito',
            'VE-S-27': 'San Pedro del Río',
            'VE-S-28': 'Santa Ana Táchira',
            'VE-S-29': 'Seboruco',
            'VE-S-30': 'Táriba',
            'VE-S-31': 'Umuquena',
            'VE-S-32': 'Ureña'
        }],
        'VE-T': [{
            'VE-T-1' : 'Batatal',
            'VE-T-2' : 'Betijoque',
            'VE-T-3' : 'Boconó',
            'VE-T-4' : 'Carache',
            'VE-T-5' : 'Chejende',
            'VE-T-6' : 'Cuicas',
            'VE-T-7' : 'El Dividive',
            'VE-T-8' : 'El Jaguito',
            'VE-T-9' : 'Escuque',
            'VE-T-10': 'Isnotú',
            'VE-T-11': 'Jajó',
            'VE-T-12': 'La Ceiba',
            'VE-T-13': 'La Concepción de Trujllo',
            'VE-T-14': 'La Mesa de Esnujaque',
            'VE-T-15': 'La Puerta',
            'VE-T-16': 'La Quebrada',
            'VE-T-17': 'Mendoza Fría',
            'VE-T-18': 'Meseta de Chimpire',
            'VE-T-19': 'Monay',
            'VE-T-20': 'Motatán',
            'VE-T-21': 'Pampán',
            'VE-T-22': 'Pampanito',
            'VE-T-23': 'Sabana de Mendoza',
            'VE-T-24': 'San Lázaro',
            'VE-T-25': 'Santa Ana de Trujillo',
            'VE-T-26': 'Tostós',
            'VE-T-27': 'Trujillo',
            'VE-T-28': 'Valera'
        }],
        'VE-U': [{
            'VE-U-1' : 'Aroa',
            'VE-U-2' : 'Boraure',
            'VE-U-3' : 'Campo Elías de Yaracuy',
            'VE-U-4' : 'Chivacoa',
            'VE-U-5' : 'Cocorote',
            'VE-U-6' : 'Farriar',
            'VE-U-7' : 'Guama',
            'VE-U-8' : 'Marín',
            'VE-U-9' : 'Nirgua',
            'VE-U-10': 'Sabana de Parra',
            'VE-U-11': 'Salom',
            'VE-U-12': 'San Felipe',
            'VE-U-13': 'San Pablo de Yaracuy',
            'VE-U-14': 'Urachiche',
            'VE-U-15': 'Yaritagua',
            'VE-U-16': 'Yumare'
        }],
        'VE-V': [{
            'VE-V-1' : 'Bachaquero',
            'VE-V-2' : 'Bobures',
            'VE-V-3' : 'Cabimas',
            'VE-V-4' : 'Campo Concepción',
            'VE-V-5' : 'Campo Mara',
            'VE-V-6' : 'Campo Rojo',
            'VE-V-7' : 'Carrasquero',
            'VE-V-8' : 'Casigua',
            'VE-V-9' : 'Chiquinquirá',
            'VE-V-10': 'Ciudad Ojeda',
            'VE-V-11': 'El Batey',
            'VE-V-12': 'El Carmelo',
            'VE-V-13': 'El Chivo',
            'VE-V-14': 'El Guayabo',
            'VE-V-15': 'El Mene',
            'VE-V-16': 'El Venado',
            'VE-V-17': 'Encontrados',
            'VE-V-18': 'Gibraltar',
            'VE-V-19': 'Isla de Toas',
            'VE-V-20': 'La Concepción del Zulia',
            'VE-V-21': 'La Paz',
            'VE-V-22': 'La Sierrita',
            'VE-V-23': 'Lagunillas del Zulia',
            'VE-V-24': 'Las Piedras de Perijá',
            'VE-V-25': 'Los Cortijos',
            'VE-V-26': 'Machiques',
            'VE-V-27': 'Maracaibo',
            'VE-V-28': 'Mene Grande',
            'VE-V-29': 'Palmarejo',
            'VE-V-30': 'Paraguaipoa',
            'VE-V-31': 'Potrerito',
            'VE-V-32': 'Pueblo Nuevo del Zulia',
            'VE-V-33': 'Puertos de Altagracia',
            'VE-V-34': 'Punta Gorda',
            'VE-V-35': 'Sabaneta de Palma',
            'VE-V-36': 'San Francisco',
            'VE-V-37': 'San José de Perijá',
            'VE-V-38': 'San Rafael del Moján',
            'VE-V-39': 'San Timoteo',
            'VE-V-40': 'Santa Bárbara Del Zulia',
            'VE-V-41': 'Santa Cruz de Mara',
            'VE-V-42': 'Santa Cruz del Zulia',
            'VE-V-43': 'Santa Rita',
            'VE-V-44': 'Sinamaica',
            'VE-V-45': 'Tamare',
            'VE-V-46': 'Tía Juana',
            'VE-V-47': 'Villa del Rosario'
        }],
        'VE-W': [{
            'VE-W-1' : 'Archipiélago Los Monjes',
            'VE-W-2' : 'Archipiélago Los Roques',
            'VE-W-3' : 'Isla La Tortuga y Cayos adyacentes',
            'VE-W-4' : 'Isla La Sola',
            'VE-W-5' : 'Islas Los Testigos',
            'VE-W-6' : 'Islas Los Frailes',
            'VE-W-7' : 'Isla La Orchila',
            'VE-W-8' : 'Archipiélago Las Aves',
            'VE-W-9' : 'Isla de Aves',
            'VE-W-10': 'Isla La Blanquilla',
            'VE-W-11': 'Isla de Patos',
            'VE-W-12': 'Islas Los Hermanos'
        }],
        'VE-X': [{
            'VE-X-1' : 'Carayaca',
            'VE-X-2' : 'Litoral',
            'VE-X-3' : 'La Guaira',
            'VE-X-4' : 'Catia La Mar',
            'VE-X-5' : 'Macuto',
            'VE-X-6' : 'Naiguatá'
        }],
        'VE-Y': [{
            'VE-Y-1' : 'Tucupita'
        }],
        'VE-Z': [{
            'VE-Z-1' : 'Maroa',
            'VE-Z-2' : 'Puerto Ayacucho',
            'VE-Z-3' : 'San Fernando de Atabapo'
        }]
    }]
}]

export { Cities };
